<?php
require_once __DIR__ . '/includes/config.php';
$page_title = 'Risk disclosure ᐉ ' . SITE_NAME;
$page_description = 'Risk disclosure — ' . SITE_NAME;
$page_canonical = page_url("risk-disclosure.php");
$active_page = "risk";
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main itemscope itemtype="https://schema.org/WebPage" id="yfln8q">
<section class="ykzi1">
  <div class="ggh3sm">
    <span class="vd7z9k">Important</span>
    <h1>Risk disclosure</h1>
    <p class="rmct9">Please read this notice carefully before using <?= e(SITE_NAME) ?> or any related service.</p>
  </div>
</section>

<section class="bqfjng">
  <div class="ggh3sm">
    <p class="cs7fii">Last updated: January 2025</p>

    <div class="ntr9c">
      <strong>Investment involves risk.</strong> The value of investments can go down as well as up. You may lose some or all of the capital you invest. <strong>Past performance is not a reliable indicator of future results.</strong> Only invest money you can afford to lose.
    </div>

    <h2>1. General warning</h2>
    <p>Trading and investing in financial instruments, cryptocurrencies and other digital assets involves a high level of risk and may not be suitable for all investors. Before deciding to use <?= e(SITE_NAME) ?>, you should carefully consider your investment objectives, your level of experience and your risk tolerance.</p>

    <h2>2. Market risk</h2>
    <p>Prices of financial instruments and digital assets can fluctuate significantly over short periods due to market conditions, macroeconomic events, regulatory developments, liquidity conditions and other factors outside our control. Losses can exceed initial deposits on leveraged products.</p>

    <h2>3. Digital asset volatility</h2>
    <p>Cryptocurrencies and other digital assets are particularly volatile. Their value can be affected by network events, forks, exchange outages, hacking or a sudden loss of confidence. There is no guarantee that any digital asset will maintain any particular value or remain tradeable.</p>

    <h2>4. Leverage risk</h2>
    <p>Where leverage is available, it amplifies both gains and losses. A relatively small market movement can result in a proportionally larger movement in the value of your position, and may result in the total loss of your funds or in amounts owed that exceed your deposit.</p>

    <h2>5. Technology and execution risk</h2>
    <p>Online trading platforms can be affected by disruptions such as system failures, delays, connectivity issues and cyber-attacks. These may prevent orders from being executed at the requested prices, or from being executed at all.</p>

    <h2>6. No investment advice</h2>
    <p>Information provided by <?= e(SITE_NAME) ?>, including any signals generated by artificial intelligence, dashboards, education or analysis, is for information purposes only and does not constitute personalised investment advice, a recommendation or a solicitation to buy or sell any financial instrument. You are solely responsible for your own investment decisions.</p>

    <h2>7. Past performance</h2>
    <p><strong>Past performance is not a reliable indicator of future performance.</strong> Backtests, simulations, model returns and hypothetical results have inherent limitations and do not reflect actual trading results.</p>

    <h2>8. Regulatory and tax considerations</h2>
    <p>The regulatory treatment of financial instruments and digital assets varies by jurisdiction and is evolving. You are responsible for understanding and complying with the laws that apply to you, including tax obligations arising from your activities.</p>

    <h2>9. Seek independent advice</h2>
    <p>If you have any doubt about the suitability of any product or service offered through <?= e(SITE_NAME) ?>, you should seek independent professional advice before proceeding.</p>

    <p style="margin-top:36px"><a class="qou73xg ec2hno" href="<?= page_url() ?>">← Back to home</a></p>
  </div>
</section>
</main>
<?php require __DIR__ . '/includes/site-footer.php'; ?>
<?php require __DIR__ . '/includes/footer.php'; ?>
