<?php

return [
    'allow_registration' => env('OFFERRA_ALLOW_REGISTRATION', false),
    'purge_local_after_deploy' => env('OFFERRA_PURGE_LOCAL_AFTER_DEPLOY', true),

    'templates_path' => base_path(env('TEMPLATES_PATH', 'templates')),
    'offers_path' => base_path(env('OFFERS_PATH', 'offers')),

    // Мови, для яких є/будуть переклади шаблонів
    'languages' => [
        ['code' => 'it', 'name' => 'Italiano'],
        ['code' => 'en', 'name' => 'English'],
        ['code' => 'es', 'name' => 'Español'],
        ['code' => 'pt', 'name' => 'Português'],
        ['code' => 'de', 'name' => 'Deutsch'],
        ['code' => 'tr', 'name' => 'Türkçe'],
        ['code' => 'da', 'name' => 'Dansk'],
        ['code' => 'ro', 'name' => 'Română'],
        ['code' => 'ka', 'name' => 'ქართული'],
        ['code' => 'cs', 'name' => 'Čeština'],
        ['code' => 'sk', 'name' => 'Slovenčina'],
        ['code' => 'hr', 'name' => 'Hrvatski'],
    ],

    // Підказки GEO — можна вибрати або вписати свій код (2 літери)
    'geo_presets' => [
        ['code' => 'IT', 'name' => 'Італія', 'lang' => 'it', 'phone' => 'it'],
        ['code' => 'IE', 'name' => 'Ірландія', 'lang' => 'en', 'phone' => 'ie'],
        ['code' => 'GB', 'name' => 'Велика Британія', 'lang' => 'en', 'phone' => 'gb'],
        ['code' => 'DE', 'name' => 'Німеччина', 'lang' => 'de', 'phone' => 'de'],
        ['code' => 'CH', 'name' => 'Швейцарія', 'lang' => 'de', 'phone' => 'ch'],
        ['code' => 'AT', 'name' => 'Австрія', 'lang' => 'de', 'phone' => 'at'],
        ['code' => 'FR', 'name' => 'Франція', 'lang' => 'en', 'phone' => 'fr'],
        ['code' => 'ES', 'name' => 'Іспанія', 'lang' => 'es', 'phone' => 'es'],
        ['code' => 'PT', 'name' => 'Португалія', 'lang' => 'pt', 'phone' => 'pt'],
        ['code' => 'NL', 'name' => 'Нідерланди', 'lang' => 'en', 'phone' => 'nl'],
        ['code' => 'BE', 'name' => 'Бельгія', 'lang' => 'en', 'phone' => 'be'],
        ['code' => 'PL', 'name' => 'Польща', 'lang' => 'en', 'phone' => 'pl'],
        ['code' => 'CZ', 'name' => 'Чехія', 'lang' => 'cs', 'phone' => 'cz'],
        ['code' => 'SK', 'name' => 'Словаччина', 'lang' => 'sk', 'phone' => 'sk'],
        ['code' => 'HU', 'name' => 'Угорщина', 'lang' => 'en', 'phone' => 'hu'],
        ['code' => 'RO', 'name' => 'Румунія', 'lang' => 'ro', 'phone' => 'ro'],
        ['code' => 'BG', 'name' => 'Болгарія', 'lang' => 'en', 'phone' => 'bg'],
        ['code' => 'GR', 'name' => 'Греція', 'lang' => 'en', 'phone' => 'gr'],
        ['code' => 'HR', 'name' => 'Хорватія', 'lang' => 'hr', 'phone' => 'hr'],
        ['code' => 'TR', 'name' => 'Туреччина', 'lang' => 'tr', 'phone' => 'tr'],
        ['code' => 'DK', 'name' => 'Данія', 'lang' => 'da', 'phone' => 'dk'],
        ['code' => 'SE', 'name' => 'Швеція', 'lang' => 'en', 'phone' => 'se'],
        ['code' => 'NO', 'name' => 'Норвегія', 'lang' => 'en', 'phone' => 'no'],
        ['code' => 'FI', 'name' => 'Фінляндія', 'lang' => 'en', 'phone' => 'fi'],
        ['code' => 'ZA', 'name' => 'ПАР', 'lang' => 'en', 'phone' => 'za'],
        ['code' => 'AR', 'name' => 'Аргентина', 'lang' => 'es', 'phone' => 'ar'],
        ['code' => 'BR', 'name' => 'Бразилія', 'lang' => 'pt', 'phone' => 'br'],
        ['code' => 'MX', 'name' => 'Мексика', 'lang' => 'es', 'phone' => 'mx'],
        ['code' => 'CL', 'name' => 'Чилі', 'lang' => 'es', 'phone' => 'cl'],
        ['code' => 'CO', 'name' => 'Колумбія', 'lang' => 'es', 'phone' => 'co'],
        ['code' => 'GE', 'name' => 'Грузія', 'lang' => 'ka', 'phone' => 'ge'],
        ['code' => 'AU', 'name' => 'Австралія', 'lang' => 'en', 'phone' => 'au'],
        ['code' => 'CA', 'name' => 'Канада', 'lang' => 'en', 'phone' => 'ca'],
        ['code' => 'US', 'name' => 'США', 'lang' => 'en', 'phone' => 'us'],
        ['code' => 'AE', 'name' => 'ОАЕ', 'lang' => 'en', 'phone' => 'ae'],
        ['code' => 'IN', 'name' => 'Індія', 'lang' => 'en', 'phone' => 'in'],
        ['code' => 'JP', 'name' => 'Японія', 'lang' => 'en', 'phone' => 'jp'],
        ['code' => 'KR', 'name' => 'Південна Корея', 'lang' => 'en', 'phone' => 'kr'],
        ['code' => 'SG', 'name' => 'Сінгапур', 'lang' => 'en', 'phone' => 'sg'],
        ['code' => 'MY', 'name' => 'Малайзія', 'lang' => 'en', 'phone' => 'my'],
        ['code' => 'TH', 'name' => 'Таїланд', 'lang' => 'en', 'phone' => 'th'],
        ['code' => 'PH', 'name' => 'Філіппіни', 'lang' => 'en', 'phone' => 'ph'],
        ['code' => 'NZ', 'name' => 'Нова Зеландія', 'lang' => 'en', 'phone' => 'nz'],
    ],
];
