<?php

return [
    'allow_registration' => env('OFFERRA_ALLOW_REGISTRATION', false),
    'purge_local_after_deploy' => env('OFFERRA_PURGE_LOCAL_AFTER_DEPLOY', true),

    // Max parallel SFTP deploys per Hestia host (match supervisor deploy workers).
    'deploy_concurrency_per_host' => (int) env('OFFERRA_DEPLOY_CONCURRENCY', 5),

    // Neutral CDN host for mirror beacons (pixel/css/boot). Example: cdnedge.io
    'cdn_probe_host' => env('CDN_PROBE_HOST', 'cdnedge.io'),

    // TLD для швидкого пошуку (без зони в полі). Іншу зону — вкажіть повний домен, напр. brand.io
    'domain_search_tlds' => [
        'click', 'cyou', 'sbs', 'cfd', 'pics', 'live', 'online', 'co',
    ],

    'templates_path' => base_path(env('TEMPLATES_PATH', 'templates')),
    'offers_path' => base_path(env('OFFERS_PATH', 'offers')),

    // Мови, для яких є/будуть переклади шаблонів
    'languages' => [
        ['code' => 'it', 'name' => 'Italiano'],
        ['code' => 'en', 'name' => 'English'],
        ['code' => 'es', 'name' => 'Español'],
        ['code' => 'pt', 'name' => 'Português'],
        ['code' => 'de', 'name' => 'Deutsch'],
        ['code' => 'tr', 'name' => 'Türkçe'],
        ['code' => 'da', 'name' => 'Dansk'],
        ['code' => 'ro', 'name' => 'Română'],
        ['code' => 'ka', 'name' => 'ქართული'],
        ['code' => 'cs', 'name' => 'Čeština'],
        ['code' => 'sk', 'name' => 'Slovenčina'],
        ['code' => 'hu', 'name' => 'Magyar'],
        ['code' => 'pl', 'name' => 'Polski'],
        ['code' => 'hr', 'name' => 'Hrvatski'],
        ['code' => 'fr', 'name' => 'Français'],
        ['code' => 'nl', 'name' => 'Nederlands'],
        ['code' => 'no', 'name' => 'Norsk'],
        ['code' => 'sv', 'name' => 'Svenska'],
        ['code' => 'fi', 'name' => 'Suomi'],
        ['code' => 'el', 'name' => 'Ελληνικά'],
        ['code' => 'ms', 'name' => 'Bahasa Melayu'],
        ['code' => 'ja', 'name' => '日本語'],
    ],

    // ISO 4217 — вибір при створенні оффера
    'currencies' => [
        ['code' => 'EUR', 'name' => 'Євро (€)'],
        ['code' => 'USD', 'name' => 'Долар США ($)'],
        ['code' => 'GBP', 'name' => 'Фунт стерлінгів (£)'],
        ['code' => 'CHF', 'name' => 'Швейцарський франк (CHF)'],
        ['code' => 'PLN', 'name' => 'Польський злотий (zł)'],
        ['code' => 'CZK', 'name' => 'Чеська крона'],
        ['code' => 'SEK', 'name' => 'Шведська крона'],
        ['code' => 'NOK', 'name' => 'Норвезька крона'],
        ['code' => 'DKK', 'name' => 'Данська крона'],
        ['code' => 'HUF', 'name' => 'Угорський форинт'],
        ['code' => 'RON', 'name' => 'Румунський лей'],
        ['code' => 'BGN', 'name' => 'Болгарський лев'],
        ['code' => 'TRY', 'name' => 'Турецька ліра (₺)'],
        ['code' => 'GEL', 'name' => 'Грузинський ларі (₾)'],
        ['code' => 'ARS', 'name' => 'Аргентинське песо'],
        ['code' => 'BRL', 'name' => 'Бразильський реал (R$)'],
        ['code' => 'MXN', 'name' => 'Мексиканське песо'],
        ['code' => 'CLP', 'name' => 'Чилійське песо'],
        ['code' => 'COP', 'name' => 'Колумбійське песо'],
        ['code' => 'PEN', 'name' => 'Перуанський соль'],
        ['code' => 'ZAR', 'name' => 'Південноафриканський ранд'],
        ['code' => 'NGN', 'name' => 'Нігерійська найра (₦)'],
        ['code' => 'AUD', 'name' => 'Австралійський долар'],
        ['code' => 'CAD', 'name' => 'Канадський долар'],
        ['code' => 'NZD', 'name' => 'Новозеландський долар'],
        ['code' => 'JPY', 'name' => 'Японська єна (¥)'],
        ['code' => 'KRW', 'name' => 'Південнокорейська вона (₩)'],
        ['code' => 'SGD', 'name' => 'Сінгапурський долар'],
        ['code' => 'MYR', 'name' => 'Малайзійський ринггіт (RM)'],
        ['code' => 'THB', 'name' => 'Тайський бат (฿)'],
        ['code' => 'PHP', 'name' => 'Філіппінське песо'],
        ['code' => 'INR', 'name' => 'Індійська рупія (₹)'],
        ['code' => 'AED', 'name' => 'Дирхам ОАЕ'],
        ['code' => 'SAR', 'name' => 'Саудівський ріял'],
        ['code' => 'ILS', 'name' => 'Ізраїльський шекель (₪)'],
        ['code' => 'CNY', 'name' => 'Китайський юань (¥)'],
        ['code' => 'HKD', 'name' => 'Гонконгський долар'],
    ],

    // Підказки GEO — можна вибрати або вписати свій код (2 літери)
    'geo_presets' => [
        ['code' => 'IT', 'name' => 'Італія', 'lang' => 'it', 'phone' => 'it'],
        ['code' => 'IE', 'name' => 'Ірландія', 'lang' => 'en', 'phone' => 'ie'],
        ['code' => 'GB', 'name' => 'Велика Британія', 'lang' => 'en', 'phone' => 'gb'],
        ['code' => 'DE', 'name' => 'Німеччина', 'lang' => 'de', 'phone' => 'de'],
        ['code' => 'CH', 'name' => 'Швейцарія', 'lang' => 'de', 'phone' => 'ch', 'currency' => 'CHF'],
        ['code' => 'AT', 'name' => 'Австрія', 'lang' => 'de', 'phone' => 'at'],
        ['code' => 'FR', 'name' => 'Франція', 'lang' => 'fr', 'phone' => 'fr'],
        ['code' => 'ES', 'name' => 'Іспанія', 'lang' => 'es', 'phone' => 'es'],
        ['code' => 'PT', 'name' => 'Португалія', 'lang' => 'pt', 'phone' => 'pt'],
        ['code' => 'NL', 'name' => 'Нідерланди', 'lang' => 'nl', 'phone' => 'nl'],
        ['code' => 'BE', 'name' => 'Бельгія', 'lang' => 'en', 'phone' => 'be'],
        ['code' => 'PL', 'name' => 'Польща', 'lang' => 'pl', 'phone' => 'pl'],
        ['code' => 'CZ', 'name' => 'Чехія', 'lang' => 'cs', 'phone' => 'cz'],
        ['code' => 'SK', 'name' => 'Словаччина', 'lang' => 'sk', 'phone' => 'sk'],
        ['code' => 'HU', 'name' => 'Угорщина', 'lang' => 'hu', 'phone' => 'hu'],
        ['code' => 'RO', 'name' => 'Румунія', 'lang' => 'ro', 'phone' => 'ro'],
        ['code' => 'BG', 'name' => 'Болгарія', 'lang' => 'en', 'phone' => 'bg'],
        ['code' => 'GR', 'name' => 'Греція', 'lang' => 'el', 'phone' => 'gr'],
        ['code' => 'HR', 'name' => 'Хорватія', 'lang' => 'hr', 'phone' => 'hr'],
        ['code' => 'TR', 'name' => 'Туреччина', 'lang' => 'tr', 'phone' => 'tr'],
        ['code' => 'DK', 'name' => 'Данія', 'lang' => 'da', 'phone' => 'dk'],
        ['code' => 'SE', 'name' => 'Швеція', 'lang' => 'sv', 'phone' => 'se', 'currency' => 'SEK'],
        ['code' => 'NO', 'name' => 'Норвегія', 'lang' => 'no', 'phone' => 'no'],
        ['code' => 'FI', 'name' => 'Фінляндія', 'lang' => 'fi', 'phone' => 'fi'],
        ['code' => 'ZA', 'name' => 'ПАР', 'lang' => 'en', 'phone' => 'za'],
        ['code' => 'NG', 'name' => 'Нігерія', 'lang' => 'en', 'phone' => 'ng', 'currency' => 'NGN'],
        ['code' => 'AR', 'name' => 'Аргентина', 'lang' => 'es', 'phone' => 'ar'],
        ['code' => 'BR', 'name' => 'Бразилія', 'lang' => 'pt', 'phone' => 'br'],
        ['code' => 'MX', 'name' => 'Мексика', 'lang' => 'es', 'phone' => 'mx'],
        ['code' => 'CL', 'name' => 'Чилі', 'lang' => 'es', 'phone' => 'cl'],
        ['code' => 'CO', 'name' => 'Колумбія', 'lang' => 'es', 'phone' => 'co'],
        ['code' => 'GE', 'name' => 'Грузія', 'lang' => 'ka', 'phone' => 'ge'],
        ['code' => 'AU', 'name' => 'Австралія', 'lang' => 'en', 'phone' => 'au'],
        ['code' => 'CA', 'name' => 'Канада', 'lang' => 'en', 'phone' => 'ca'],
        ['code' => 'US', 'name' => 'США', 'lang' => 'en', 'phone' => 'us'],
        ['code' => 'AE', 'name' => 'ОАЕ', 'lang' => 'en', 'phone' => 'ae'],
        ['code' => 'IN', 'name' => 'Індія', 'lang' => 'en', 'phone' => 'in'],
        ['code' => 'JP', 'name' => 'Японія', 'lang' => 'ja', 'phone' => 'jp', 'currency' => 'JPY'],
        ['code' => 'KR', 'name' => 'Південна Корея', 'lang' => 'en', 'phone' => 'kr'],
        ['code' => 'SG', 'name' => 'Сінгапур', 'lang' => 'en', 'phone' => 'sg'],
        ['code' => 'MY', 'name' => 'Малайзія', 'lang' => 'ms', 'phone' => 'my', 'currency' => 'MYR'],
        ['code' => 'TH', 'name' => 'Таїланд', 'lang' => 'en', 'phone' => 'th'],
        ['code' => 'PH', 'name' => 'Філіппіни', 'lang' => 'en', 'phone' => 'ph'],
        ['code' => 'NZ', 'name' => 'Нова Зеландія', 'lang' => 'en', 'phone' => 'nz'],
    ],
];
