import { rows, add } from './_rows-a.mjs';

// Markets / How / Payment
add('Opere Bitcoin, Ethereum e muito mais', 'Tradez Bitcoin, Ethereum et bien plus', 'Opera Bitcoin, Ethereum e molto altro', 'Opera Bitcoin, Ethereum y mucho más');
add('Preços em tempo real, indicadores avançados e uma visão profissional dos mercados que interessam a si.', 'Prix en temps réel, indicateurs avancés et une vision professionnelle des marchés qui vous intéressent.', 'Prezzi in tempo reale, indicatori avanzati e una visione professionale dei mercati che ti interessano.', 'Precios en tiempo real, indicadores avanzados y una visión profesional de los mercados que te interesan.');
add('Quero acesso aos mercados', 'Je veux accéder aux marchés', 'Voglio accedere ai mercati', 'Quiero acceso a los mercados');
add('Direto', 'En direct', 'Live', 'En directo');
add('Tecnologia de ponta e um analista humano de verdade, trabalhando juntos em tempo real, para ajudar a construir uma nova fonte de renda — com orientação em cada etapa.', 'Une technologie de pointe et un véritable analyste humain, travaillant ensemble en temps réel, pour vous aider à construire une nouvelle source de revenus — avec un accompagnement à chaque étape.', "Tecnologia all'avanguardia e un vero analista umano, che lavorano insieme in tempo reale per aiutarti a costruire una nuova fonte di reddito — con guida in ogni fase.", 'Tecnología de punta y un analista humano de verdad, trabajando juntos en tiempo real, para ayudarte a construir una nueva fuente de ingresos — con orientación en cada etapa.');
add('Crie sua conta', 'Créez votre compte', 'Crea il tuo account', 'Crea tu cuenta');
add('Cadastre-se em minutos usando apenas seu e-mail.', 'Inscrivez-vous en quelques minutes avec seulement votre e-mail.', 'Registrati in pochi minuti usando solo la tua e-mail.', 'Regístrate en minutos usando solo tu correo.');
add('Confirme seu e-mail', 'Confirmez votre e-mail', 'Conferma la tua e-mail', 'Confirma tu correo');
add('Verifique seu endereço para proteger sua conta.', 'Vérifiez votre adresse pour sécuriser votre compte.', "Verifica il tuo indirizzo per proteggere l'account.", 'Verifica tu dirección para proteger tu cuenta.');
add('Deposite na sua conta', 'Déposez sur votre compte', 'Deposita sul tuo account', 'Deposita en tu cuenta');
add('Adicione fundos a partir de', 'Ajoutez des fonds à partir de', 'Aggiungi fondi a partire da', 'Añade fondos a partir de');
add(' do seu jeito.', ' à votre façon.', ' a modo tuo.', ' a tu manera.');
add('Defina sua estratégia', 'Définissez votre stratégie', 'Definisci la tua strategia', 'Define tu estrategia');
add('Escolha seus objetivos; seu analista personaliza o plano.', 'Choisissez vos objectifs ; votre analyste personnalise le plan.', 'Scegli i tuoi obiettivi; il tuo analista personalizza il piano.', 'Elige tus objetivos; tu analista personaliza el plan.');
add('Comece a operar', 'Commencez à trader', 'Inizia a operare', 'Empieza a operar');
add('Siga os sinais guiados e cresça no seu ritmo.', 'Suivez les signaux guidés et progressez à votre rythme.', 'Segui i segnali guidati e cresci al tuo ritmo.', 'Sigue las señales guiadas y crece a tu ritmo.');
add('Depósitos', 'Dépôts', 'Depositi', 'Depósitos');
add('Deposite com métodos que já conhece', 'Déposez avec des méthodes que vous connaissez déjà', 'Deposita con metodi che conosci già', 'Deposita con métodos que ya conoces');
add('Deposite e retire por canais seguros e familiares — sem taxas escondidas.', 'Déposez et retirez via des canaux sécurisés et familiers — sans frais cachés.', 'Deposita e preleva tramite canali sicuri e familiari — senza costi nascosti.', 'Deposita y retira por canales seguros y familiares — sin comisiones ocultas.');

// Testimonials
add('O que dizem os membros', 'Ce que disent les membres', 'Cosa dicono i membri', 'Lo que dicen los miembros');
add('O que nossos investidores dizem', 'Ce que disent nos investisseurs', 'Cosa dicono i nostri investitori', 'Lo que dicen nuestros inversores');
add('“Meu analista me explicou tudo com clareza. Defini meus objetivos uma única vez, e agora acompanho exatamente como meu capital está crescendo — sem ficar ansioso a cada movimento.”', '« Mon analyste m’a tout expliqué clairement. J’ai défini mes objectifs une seule fois, et maintenant je suis exactement comment mon capital croît — sans angoisse à chaque mouvement. »', '« Il mio analista mi ha spiegato tutto con chiarezza. Ho definito i miei obiettivi una sola volta e ora seguo esattamente come cresce il mio capitale — senza ansia a ogni movimento. »', '« Mi analista me lo explicó todo con claridad. Definí mis objetivos una sola vez, y ahora sigo exactamente cómo crece mi capital — sin ansiedad en cada movimiento. »');
add('Carolina Machado', 'Camille Dupont', 'Giulia Rossi', 'Carla Mendoza');
add('São Paulo, SP', 'Paris', 'Roma', 'Madrid');
add('“Nunca havia investido antes — meu analista cuidou da estratégia e explicou cada passo. Sem promessas vazias, sem pressão, e os saques chegam quando esperado.”', '« Je n’avais jamais investi auparavant — mon analyste a géré la stratégie et expliqué chaque étape. Pas de fausses promesses, pas de pression, et les retraits arrivent comme prévu. »', '« Non avevo mai investito prima — il mio analista ha gestito la strategia e spiegato ogni passo. Niente promesse vuote, niente pressione, e i prelievi arrivano quando previsto. »', '« Nunca había invertido antes — mi analista cuidó la estrategia y explicó cada paso. Sin promesas vacías, sin presión, y los retiros llegan cuando se espera. »');
add('Felipe Santos', 'Thomas Bernard', 'Marco Bianchi', 'Pablo Ruiz');
add('Rio de Janeiro, RJ', 'Lyon', 'Milano', 'Barcelona');
add('“Comecei com pouco para testar. A transparência e o suporte me deram segurança para continuar construindo a partir daí.”', '« J’ai commencé avec peu pour tester. La transparence et le support m’ont donné confiance pour continuer à construire. »', '« Ho iniziato con poco per testare. La trasparenza e il supporto mi hanno dato sicurezza per continuare a costruire. »', '« Empecé con poco para probar. La transparencia y el soporte me dieron seguridad para seguir construyendo. »');
add('Beatriz Lima', 'Sophie Martin', 'Elena Conti', 'Lucía Torres');
add('Belo Horizonte, MG', 'Marseille', 'Napoli', 'Valencia');
add('“As análises chegam até mim — aprovo ou ajusto em minutos. Encaixa perfeitamente na minha rotina, sem atrapalhar o trabalho.”', '« Les analyses me parviennent — j’approuve ou j’ajuste en quelques minutes. Ça s’intègre parfaitement à ma routine, sans gêner le travail. »', '« Le analisi arrivano a me — approvo o correggo in pochi minuti. Si adatta perfettamente alla mia routine, senza interferire con il lavoro. »', '« Los análisis me llegan — apruebo o ajusto en minutos. Encaja perfectamente en mi rutina, sin interferir en el trabajo. »');
add('Lucas Ferreira', 'Antoine Lefèvre', 'Luca Ferrari', 'Javier Ortega');
add('Brasília, DF', 'Toulouse', 'Torino', 'Sevilla');
add('“O que me conquistou foi a transparência: cada decisão é explicada, e vejo o raciocínio antes de qualquer coisa acontecer.”', '« Ce qui m’a convaincu, c’est la transparence : chaque décision est expliquée, et je vois le raisonnement avant que quoi que ce soit se produise. »', '« Ciò che mi ha conquistato è la trasparenza: ogni decisione è spiegata e vedo il ragionamento prima che accada qualsiasi cosa. »', '« Lo que me conquistó fue la transparencia: cada decisión se explica, y veo el razonamiento antes de que ocurra nada. »');
add('Gabriela Costa', 'Léa Moreau', 'Chiara Esposito', 'María Gómez');
add('Salvador, BA', 'Nice', 'Bologna', 'Bilbao');
add('“O suporte é de verdade e sempre acessível. Minha primeira análise foi feita mão na massa, e a plataforma tem sido firme e previsível desde então.”', '« Le support est réel et toujours accessible. Ma première analyse a été concrète, et la plateforme est restée stable et prévisible depuis. »', '« Il supporto è reale e sempre accessibile. La mia prima analisi è stata pratica, e la piattaforma è stata solida e prevedibile da allora. »', '« El soporte es de verdad y siempre accesible. Mi primer análisis fue práctico, y la plataforma ha sido firme y predecible desde entonces. »');
add('Roberto Oliveira', 'Nicolas Petit', 'Andrea Ricci', 'Miguel Navarro');
add('Curitiba, PR', 'Bordeaux', 'Firenze', 'Málaga');

// Capabilities
add('Principais recursos, em resumo', 'Principales fonctionnalités, en bref', 'Funzionalità principali, in sintesi', 'Funciones principales, en resumen');
add('Motor de IA', "Moteur d'IA", 'Motore di IA', 'Motor de IA');
add('Análise avançada de mercado com aprendizado de máquina', "Analyse avancée des marchés avec apprentissage automatique", 'Analisi avanzata di mercato con machine learning', 'Análisis avanzado de mercado con aprendizaje automático');
add('Formas de depósito', 'Modes de dépôt', 'Metodi di deposito', 'Formas de depósito');
add('Cartão de crédito, transferência bancária, PayPal, carteiras digitais', 'Carte de crédit, virement bancaire, PayPal, portefeuilles numériques', 'Carta di credito, bonifico bancario, PayPal, wallet digitali', 'Tarjeta de crédito, transferencia bancaria, PayPal, monederos digitales');
add('Acesso multiplataforma', 'Accès multiplateforme', 'Accesso multipiattaforma', 'Acceso multiplataforma');
add('Web, tablet e celular — totalmente responsivo', 'Web, tablette et mobile — entièrement responsive', 'Web, tablet e mobile — totalmente responsive', 'Web, tablet y móvil — totalmente responsive');
add('Precisão dos sinais', 'Précision des signaux', 'Precisione dei segnali', 'Precisión de las señales');
add('Até 85% nas estratégias de IA suportadas', "Jusqu'à 85 % sur les stratégies d'IA prises en charge", "Fino all'85% nelle strategie di IA supportate", 'Hasta el 85% en las estrategias de IA compatibles');
add('Criptomoedas, forex, ações e commodities', 'Cryptomonnaies, forex, actions et matières premières', 'Criptovalute, forex, azioni e materie prime', 'Criptomonedas, forex, acciones y materias primas');
add('Cadastro', 'Inscription', 'Registrazione', 'Registro');
add('Abertura de conta rápida com verificação guiada', 'Ouverture de compte rapide avec vérification guidée', 'Apertura account rapida con verifica guidata', 'Apertura de cuenta rápida con verificación guiada');
add('Atendimento profissional 24 horas por dia —', 'Assistance professionnelle 24 h/24 —', 'Assistenza professionale 24 ore su 24 —', 'Atención profesional las 24 horas —');
add('Enviar mensagem', 'Envoyer un message', 'Invia un messaggio', 'Enviar mensaje');

// FAQ
add('Dúvidas', 'Questions', 'Domande', 'Dudas');
add('Qual é o depósito mínimo?', 'Quel est le dépôt minimum ?', "Qual è il deposito minimo?", '¿Cuál es el depósito mínimo?');
add('Abre e financia sua conta a partir do depósito mínimo. Pode adicionar saldo ao longo do tempo conforme seu plano avança.', 'Ouvrez et financez votre compte à partir du dépôt minimum. Vous pouvez ajouter des fonds au fil du temps à mesure que votre plan progresse.', 'Apri e finanzia il tuo account a partire dal deposito minimo. Puoi aggiungere fondi nel tempo man mano che il piano avanza.', 'Abre y financia tu cuenta a partir del depósito mínimo. Puedes añadir saldo con el tiempo a medida que avanza tu plan.');
add('Como funcionam os saques?', 'Comment fonctionnent les retraits ?', 'Come funzionano i prelievi?', '¿Cómo funcionan los retiros?');
add('Solicite um saque a qualquer momento pelo painel. Os fundos retornam ao método de pagamento escolhido, respeitando os prazos padrão de processamento.', 'Demandez un retrait à tout moment depuis le tableau de bord. Les fonds reviennent vers le moyen de paiement choisi, selon les délais de traitement standards.', 'Richiedi un prelievo in qualsiasi momento dal pannello. I fondi tornano al metodo di pagamento scelto, rispettando i tempi di elaborazione standard.', 'Solicita un retiro en cualquier momento desde el panel. Los fondos vuelven al método de pago elegido, respetando los plazos estándar de procesamiento.');
add('Meu dinheiro está seguro?', 'Mon argent est-il en sécurité ?', 'I miei soldi sono al sicuro?', '¿Mi dinero está seguro?');
add('As contas são protegidas com segurança de padrão industrial e verificação rigorosa. Como em todo investimento, seu capital está em risco e valores podem cair tanto quanto subir.', 'Les comptes sont protégés par une sécurité de niveau industriel et une vérification stricte. Comme pour tout investissement, votre capital est à risque et les valeurs peuvent baisser autant que monter.', 'I conti sono protetti con sicurezza di livello industriale e verifica rigorosa. Come in ogni investimento, il capitale è a rischio e i valori possono scendere tanto quanto salire.', 'Las cuentas están protegidas con seguridad de nivel industrial y verificación rigurosa. Como en toda inversión, tu capital está en riesgo y los valores pueden bajar tanto como subir.');
add('Com que rapidez posso começar?', 'À quelle vitesse puis-je commencer ?', 'Quanto velocemente posso iniziare?', '¿Con qué rapidez puedo empezar?');
add('A maioria dos membros conclui o registro em poucos minutos. Assim que seu primeiro depósito é confirmado, ativa um plano imediatamente.', "La plupart des membres terminent l'inscription en quelques minutes. Dès que votre premier dépôt est confirmé, un plan s'active immédiatement.", 'La maggior parte dei membri completa la registrazione in pochi minuti. Non appena il primo deposito è confermato, si attiva subito un piano.', 'La mayoría de los miembros completa el registro en pocos minutos. En cuanto se confirma tu primer depósito, se activa un plan de inmediato.');
add('Há taxas escondidas?', 'Y a-t-il des frais cachés ?', 'Ci sono costi nascosti?', '¿Hay comisiones ocultas?');
add('Os custos são mostrados com transparência antes de si se comprometer. Sempre saberá exatamente o que se aplica ao seu plano — nenhuma cobrança surpresa.', "Les coûts sont affichés en toute transparence avant que vous ne vous engagiez. Vous saurez toujours exactement ce qui s'applique à votre plan — aucun frais surprise.", 'I costi sono mostrati con trasparenza prima che tu ti impegni. Saprai sempre esattamente cosa si applica al tuo piano — nessun addebito a sorpresa.', 'Los costes se muestran con transparencia antes de que te comprometas. Siempre sabrás exactamente qué se aplica a tu plan — ningún cargo sorpresa.');
add('Qual é a idade mínima para se registrar?', "Quel est l'âge minimum pour s'inscrire ?", "Qual è l'età minima per registrarsi?", '¿Cuál es la edad mínima para registrarse?');
add('Deve ter pelo menos 18 anos para abrir uma conta e investir. Verificação pode ser exigida para confirmar sua idade e identidade.', "Vous devez avoir au moins 18 ans pour ouvrir un compte et investir. Une vérification peut être exigée pour confirmer votre âge et votre identité.", "Devi avere almeno 18 anni per aprire un account e investire. Può essere richiesta una verifica per confermare età e identità.", 'Debes tener al menos 18 años para abrir una cuenta e invertir. Puede exigirse una verificación para confirmar tu edad e identidad.');
add('Quais métodos de pagamento são suportados?', 'Quels moyens de paiement sont pris en charge ?', 'Quali metodi di pagamento sono supportati?', '¿Qué métodos de pago se admiten?');
add('Métodos comuns como cartão de débito e crédito, transferência bancária, e-wallets selecionadas e criptomoedas são suportados. As opções exatas aparecem no passo de depósito.', 'Les moyens courants comme carte de débit et de crédit, virement bancaire, e-wallets sélectionnés et cryptomonnaies sont pris en charge. Les options exactes apparaissent à l\'étape du dépôt.', 'Metodi comuni come carta di debito e credito, bonifico bancario, e-wallet selezionati e criptovalute sono supportati. Le opzioni esatte compaiono nella fase di deposito.', 'Se admiten métodos habituales como tarjeta de débito y crédito, transferencia bancaria, monederos electrónicos seleccionados y criptomonedas. Las opciones exactas aparecen en el paso de depósito.');
add('Quando o suporte ao cliente está disponível?', 'Quand le support client est-il disponible ?', 'Quando è disponibile il supporto clienti?', '¿Cuándo está disponible el soporte al cliente?');
add('Nossa equipe de suporte funciona de segunda a sexta, das 9h às 18h, e se compromete a responder cada solicitação em até um dia útil.', "Notre équipe support est disponible du lundi au vendredi, de 9 h à 18 h, et s'engage à répondre à chaque demande sous un jour ouvré.", 'Il nostro team di supporto è operativo dal lunedì al venerdì, dalle 9:00 alle 18:00, e si impegna a rispondere a ogni richiesta entro un giorno lavorativo.', 'Nuestro equipo de soporte atiende de lunes a viernes, de 9:00 a 18:00, y se compromete a responder cada solicitud en un día hábil.');
add('Como são tratados os impostos?', 'Comment les impôts sont-ils traités ?', 'Come vengono gestite le imposte?', '¿Cómo se tratan los impuestos?');
add('Os impostos sobre ganhos de investimento dependem das regras do seu país e são sua responsabilidade. Recomendamos manter registros e consultar um consultor fiscal qualificado.', 'Les impôts sur les gains d\'investissement dépendent des règles de votre pays et sont votre responsabilité. Nous recommandons de conserver des registres et de consulter un conseiller fiscal qualifié.', 'Le imposte sui guadagni da investimento dipendono dalle norme del tuo Paese e sono a tuo carico. Consigliamo di conservare i registri e consultare un consulente fiscale qualificato.', 'Los impuestos sobre ganancias de inversión dependen de las normas de tu país y son tu responsabilidad. Recomendamos guardar registros y consultar a un asesor fiscal cualificado.');
add('O que é KYC e por que é obrigatório?', "Qu'est-ce que le KYC et pourquoi est-il obligatoire ?", "Cos'è il KYC e perché è obbligatorio?", '¿Qué es el KYC y por qué es obligatorio?');
add('KYC (Conheça Seu Cliente) é uma verificação padrão da sua identidade. Mantém contas seguras e faz parte da abertura de qualquer conta de investimento.', 'Le KYC (Know Your Customer) est une vérification standard de votre identité. Il sécurise les comptes et fait partie de l\'ouverture de tout compte d\'investissement.', 'Il KYC (Know Your Customer) è una verifica standard della tua identità. Mantiene i conti al sicuro e fa parte dell\'apertura di qualsiasi conto di investimento.', 'El KYC (Conozca a su cliente) es una verificación estándar de tu identidad. Mantiene las cuentas seguras y forma parte de la apertura de cualquier cuenta de inversión.');
add('Preciso ter experiência?', "Faut-il avoir de l'expérience ?", 'Devo avere esperienza?', '¿Necesito tener experiencia?');
add('Não. Cada membro recebe um analista financeiro pessoal que o orienta a cada passo, então não precisa de conhecimento prévio de mercados.', "Non. Chaque membre reçoit un analyste financier personnel qui le guide à chaque étape, donc aucune connaissance préalable des marchés n'est nécessaire.", 'No. Ogni membro riceve un analista finanziario personale che lo guida in ogni passo, quindi non serve conoscenza previa dei mercati.', 'No. Cada miembro recibe un analista financiero personal que le orienta en cada paso, así que no hace falta conocimiento previo de los mercados.');
add('Quem gerencia meus investimentos?', 'Qui gère mes investissements ?', 'Chi gestisce i miei investimenti?', '¿Quién gestiona mis inversiones?');
add('Um analista financeiro dedicado, apoiado por ferramentas de IA, trabalhando em torno de seus objetivos e nível de risco. O analista combina expertise profissional com tecnologia — as decisões permanecem humanas.', "Un analyste financier dédié, soutenu par des outils d'IA, travaillant autour de vos objectifs et de votre niveau de risque. L'analyste allie expertise professionnelle et technologie — les décisions restent humaines.", "Un analista finanziario dedicato, supportato da strumenti di IA, che lavora sui tuoi obiettivi e sul livello di rischio. L'analista unisce expertise professionale e tecnologia — le decisioni restano umane.", 'Un analista financiero dedicado, respaldado por herramientas de IA, trabajando en torno a tus objetivos y nivel de riesgo. El analista combina experiencia profesional con tecnología — las decisiones siguen siendo humanas.');
add('A plataforma é regulamentada?', 'La plateforme est-elle réglementée ?', 'La piattaforma è regolamentata?', '¿La plataforma está regulada?');
add('Sim — atende aos padrões financeiros e de cibersegurança nacionais, com proteção de conta e verificação rigorosa integradas.', 'Oui — elle répond aux normes financières et de cybersécurité nationales, avec protection de compte et vérification stricte intégrées.', 'Sì — rispetta gli standard finanziari e di cybersecurity nazionali, con protezione del conto e verifica rigorosa integrate.', 'Sí — cumple los estándares financieros y de ciberseguridad nacionales, con protección de cuenta y verificación rigurosa integradas.');
add('Posso adicionar saldo depois?', 'Puis-je ajouter des fonds plus tard ?', 'Posso aggiungere fondi in seguito?', '¿Puedo añadir saldo después?');
add('Sim. Pode aportar na sua conta a qualquer momento e ajustar seu plano com seu analista conforme seus objetivos evoluem.', 'Oui. Vous pouvez alimenter votre compte à tout moment et ajuster votre plan avec votre analyste à mesure que vos objectifs évoluent.', 'Sì. Puoi versare sul tuo account in qualsiasi momento e adattare il piano con il tuo analista man mano che gli obiettivi evolvono.', 'Sí. Puedes aportar a tu cuenta en cualquier momento y ajustar tu plan con tu analista a medida que evolucionan tus objetivos.');

// Reviews block / CTA / footer
add('DE CONFIANÇA', 'DE CONFIANCE', 'AFFIDABILE', 'DE CONFIANZA');
add(' Avaliações', ' Avis', ' Recensioni', ' Valoraciones');
add(' avaliações · Com base em ', ' avis · Basé sur ', ' recensioni · Basato su ', ' valoraciones · Basado en ');
add(' classificações', ' notes', ' valutazioni', ' clasificaciones');
add('Diga-nos como entrar em contato e um especialista vai ajudar a dar o primeiro passo.', 'Indiquez-nous comment vous joindre et un expert vous aidera à faire le premier pas.', 'Dicci come contattarti e uno specialista ti aiuterà a fare il primo passo.', 'Dinos cómo contactarte y un especialista te ayudará a dar el primer paso.');
add('Velocidade de IA, decisão humana. Capital em risco — invista com responsabilidade.', "Vitesse de l'IA, décision humaine. Capital à risque — investissez de manière responsable.", "Velocità dell'IA, decisione umana. Capitale a rischio — investi con responsabilità.", 'Velocidad de IA, decisión humana. Capital en riesgo — invierte con responsabilidad.');
add('Investir envolve risco, incluindo possível perda de capital. · Investir envolve risco, incluindo a possível perda de parte ou de todo o capital investido. O valor dos investimentos pode subir ou cair, e pode receber de volta menos do que aplicou inicialmente. Não invista dinheiro que não pode perder.', "Investir comporte un risque, y compris une possible perte de capital. · Investir comporte un risque, y compris la possible perte d'une partie ou de la totalité du capital investi. La valeur des investissements peut monter ou baisser, et vous pouvez récupérer moins que ce que vous avez engagé. N'investissez pas d'argent que vous ne pouvez pas vous permettre de perdre.", 'Investire comporta un rischio, inclusa la possibile perdita di capitale. · Investire comporta un rischio, inclusa la possibile perdita di parte o di tutto il capitale investito. Il valore degli investimenti può salire o scendere e puoi ricevere indietro meno di quanto hai versato. Non investire denaro che non puoi permetterti di perdere.', 'Invertir implica riesgo, incluida la posible pérdida de capital. · Invertir implica riesgo, incluida la posible pérdida de parte o de todo el capital invertido. El valor de las inversiones puede subir o bajar, y puedes recuperar menos de lo que aportaste. No inviertas dinero que no puedas permitirte perder.');

console.log('after b', Object.keys(rows).length);
export { rows, add };
